apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: SampleApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: cz65rv/nodejs:Tag
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: nodejs 
spec:
  selector:
    app: nodejs 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer 
